In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
from core.Network import CountModel_cls, early_stop_callback, Backbone
from core.data import AppleRoboFlowDataModule

import lightning as L

In [6]:
dm = AppleRoboFlowDataModule()
model = CountModel_cls()

trainer = L.Trainer(max_epochs=100)

trainer.fit(model, dm)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type    | Params | Mode 
--------------------------------------------
0 | model   | ResNet  | 23.6 M | train
1 | softmax | Softmax | 0      | train
--------------------------------------------
23.6 M    Trainable params
0         Non-trainable params
23.6 M    Total params
94.262    Total estimated model params size (MB)
152       Modules in train mode
0         Modules in eval mode


loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!


c:\Users\Vaibhav\anaconda3\envs\fast\Lib\site-packages\lightning\pytorch\loops\fit_loop.py:298: The number of training batches (14) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Epoch 99: 100%|██████████| 14/14 [00:04<00:00,  2.90it/s, v_num=35]

`Trainer.fit` stopped: `max_epochs=100` reached.


Epoch 99: 100%|██████████| 14/14 [00:06<00:00,  2.32it/s, v_num=35]


In [18]:
trainer.test(model,dataloaders=dm.test_dataloader())


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Testing DataLoader 0: 100%|██████████| 4/4 [00:00<00:00,  6.05it/s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        accuracy            25.342464447021484
    accuracy_count_1        57.142860412597656
    accuracy_count_10               0.0
    accuracy_count_12               0.0
    accuracy_count_13               0.0
    accuracy_count_2         3.846153974533081
    accuracy_count_22               0.0
    accuracy_count_24               0.0
    accuracy_count_27               0.0
    accuracy_count_3        13.333333969116211
    accuracy_count_4         22.22222328186035
    accuracy_count_5                0.0
    accuracy_count_6                0.0
    accu

[{'accuracy': 25.342464447021484,
  'mae': 3.4178082942962646,
  'accuracy_count_1': 57.142860412597656,
  'accuracy_count_2': 3.846153974533081,
  'accuracy_count_3': 13.333333969116211,
  'accuracy_count_4': 22.22222328186035,
  'accuracy_count_5': 0.0,
  'accuracy_count_6': 0.0,
  'accuracy_count_7': 0.0,
  'accuracy_count_8': 0.0,
  'accuracy_count_9': 0.0,
  'accuracy_count_10': 0.0,
  'accuracy_count_12': 0.0,
  'accuracy_count_13': 0.0,
  'accuracy_count_22': 0.0,
  'accuracy_count_24': 0.0,
  'accuracy_count_27': 0.0}]

In [20]:
trainer.test(model,dataloaders=dm.train_dataloader())

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


loading annotations into memory...
Done (t=0.00s)
creating index...
index created!


c:\Users\Vaibhav\anaconda3\envs\fast\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:475: Your `test_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test dataloaders.


Testing DataLoader 0: 100%|██████████| 14/14 [00:01<00:00,  9.41it/s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        accuracy             36.16636276245117
    accuracy_count_1         70.64676666259766
    accuracy_count_10       15.384615898132324
    accuracy_count_11              50.0
    accuracy_count_12              40.0
    accuracy_count_13               0.0
    accuracy_count_14               0.0
    accuracy_count_15               0.0
    accuracy_count_16               0.0
    accuracy_count_17               0.0
    accuracy_count_18              100.0
    accuracy_count_2        13.924050331115723
    accuracy_count_20              100.0
    accuracy_count_22               0.0
    accuracy_count_23               0.0
    accuracy_c

[{'accuracy': 36.16636276245117,
  'mae': 2.535262107849121,
  'accuracy_count_1': 70.64676666259766,
  'accuracy_count_2': 13.924050331115723,
  'accuracy_count_3': 1.470588207244873,
  'accuracy_count_4': 40.0,
  'accuracy_count_5': 10.0,
  'accuracy_count_6': 33.333335876464844,
  'accuracy_count_7': 0.0,
  'accuracy_count_8': 0.0,
  'accuracy_count_9': 0.0,
  'accuracy_count_10': 15.384615898132324,
  'accuracy_count_12': 40.0,
  'accuracy_count_13': 0.0,
  'accuracy_count_22': 0.0,
  'accuracy_count_11': 50.0,
  'accuracy_count_14': 0.0,
  'accuracy_count_15': 0.0,
  'accuracy_count_16': 0.0,
  'accuracy_count_17': 0.0,
  'accuracy_count_18': 100.0,
  'accuracy_count_20': 100.0,
  'accuracy_count_23': 0.0,
  'accuracy_count_26': 100.0}]

In [8]:
import torch

batch = next(iter(dm.train_dataloader()))
print(torch.argmax(model(batch[0]), dim=1))


tensor([11,  1,  1,  1, 11,  4, 18,  1, 11,  1,  4,  1,  1,  4, 12,  1,  3,  1,
         2,  3,  1,  6,  1, 11,  3,  1, 26,  1,  1,  1,  2,  6,  4,  1,  6,  4,
         4,  6, 11,  6])


In [9]:
print(batch[1]['count'])

tensor([6, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 3, 5, 4, 1, 2, 1, 1, 3, 2, 2, 3, 1, 3,
        2, 1, 5, 1, 1, 1, 7, 4, 4, 5, 6, 1, 4, 1, 2, 3])


In [17]:
dm.setup('test')
dm.test_dataset

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!


Dataset CustomCocoDataset
    Number of datapoints: 146
    Root location: D:/DATA/APPLE/Roboflow/valid
    StandardTransform
Transform: Compose(
               RandomHorizontalFlip(p=0.5)
               RandomVerticalFlip(p=0.5)
               ToTensor()
           )

In [10]:
#script to get each count in the dataset
count = {}

for images, targets in dm.train_dataloader():
    # max_count = max(max_count, targets['count'].max().item())
    for c in targets['count']:
        c = c.item()
        if c in count:
            count[c] += 1
        else:
            count[c] = 1

# print(f"Maximum count in the dataset: {max_count}")

In [11]:
count

{1: 201,
 2: 79,
 4: 45,
 12: 10,
 5: 30,
 3: 68,
 7: 22,
 18: 4,
 14: 2,
 11: 8,
 6: 27,
 10: 13,
 13: 4,
 9: 11,
 8: 18,
 17: 3,
 22: 1,
 26: 1,
 15: 3,
 20: 1,
 23: 1,
 16: 1}

In [12]:
#percentage of each count in the dataset
total = sum(count.values())
percentage = {k: v/total for k, v in count.items()}
percentage


{1: 0.36347197106690776,
 2: 0.14285714285714285,
 4: 0.081374321880651,
 12: 0.018083182640144666,
 5: 0.054249547920433995,
 3: 0.12296564195298372,
 7: 0.039783001808318265,
 18: 0.007233273056057866,
 14: 0.003616636528028933,
 11: 0.014466546112115732,
 6: 0.048824593128390596,
 10: 0.023508137432188065,
 13: 0.007233273056057866,
 9: 0.019891500904159132,
 8: 0.0325497287522604,
 17: 0.0054249547920434,
 22: 0.0018083182640144665,
 26: 0.0018083182640144665,
 15: 0.0054249547920434,
 20: 0.0018083182640144665,
 23: 0.0018083182640144665,
 16: 0.0018083182640144665}

In [13]:

class self:
    pass
self.max_count = 28
self.count_freq = {
    3: 0.12296564195298372,
    7: 0.039783001808318265,
    12: 0.018083182640144666,
    2: 0.14285714285714285,
    5: 0.054249547920433995,
    17: 0.0054249547920434,
    14: 0.003616636528028933,
    4: 0.081374321880651,
    1: 0.36347197106690776,
    22: 0.0018083182640144665,
    6: 0.048824593128390596,
    10: 0.023508137432188065,
    8: 0.0325497287522604,
    15: 0.0054249547920434,
    9: 0.019891500904159132,
    18: 0.007233273056057866,
    11: 0.014466546112115732,
    13: 0.007233273056057866,
    20: 0.0018083182640144665,
    26: 0.0018083182640144665,
    16: 0.0018083182640144665,
    23: 0.0018083182640144665
}

for i in range(self.max_count):
    if i not in self.count_freq:
        self.count_freq[i] = 0.0018083182640144665

self.count_freq = [1/self.count_freq[i] for i in range(self.max_count)]
self.count_freq = torch.tensor(self.count_freq)
self.count_freq = self.count_freq / torch.sum(self.count_freq)
self.count_freq = self.count_freq.float().cuda()
self.count_freq

tensor([0.0753, 0.0004, 0.0010, 0.0011, 0.0017, 0.0025, 0.0028, 0.0034, 0.0042,
        0.0068, 0.0058, 0.0094, 0.0075, 0.0188, 0.0376, 0.0251, 0.0753, 0.0251,
        0.0188, 0.0753, 0.0753, 0.0753, 0.0753, 0.0753, 0.0753, 0.0753, 0.0753,
        0.0753], device='cuda:0')